# Generated by Django 4.0.6 on 2022-07-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=32)),
                ('age', models.PositiveIntegerField()),
                ('salary', models.IntegerField(blank=True)),
                ('gender', models.BooleanField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField(default='felan.')),
            ],
        ),
    ]
