# Generated by Django 4.0.6 on 2022-07-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
